# SessionEnd hook: regenerate HEALTH.md with current vault metrics + weekly review status.

. "$PSScriptRoot/_lib.ps1"

try {
    $topicsDir = Get-TopicsDir
    $logPath = Get-LogPath
    $healthPath = Get-HealthPath
    if (-not (Test-Path $topicsDir)) { exit 0 }

    $topics = Get-ChildItem $topicsDir -Filter '*.md' -ErrorAction SilentlyContinue
    $count = $topics.Count
    $totalWords = 0
    $maxWords = 0
    $stale60 = 0
    $stale180 = 0
    $never = 0
    $hot = 0
    $stable = 0
    $evolving = 0
    $ephemeral = 0
    $now = Get-Date

    foreach ($f in $topics) {
        $body = Get-Content $f.FullName -Raw -ErrorAction SilentlyContinue
        if (-not $body) { continue }
        $words = ($body -split '\s+').Count
        $totalWords += $words
        if ($words -gt $maxWords) { $maxWords = $words }

        if ($body -match '(?m)^last_updated:\s*(\S+)') {
            try {
                $d = [datetime]::Parse($matches[1])
                $age = ($now - $d).TotalDays
                if ($age -gt 60) { $stale60++ }
                if ($age -gt 180) { $stale180++ }
            } catch {}
        }
        if ($body -match '(?m)^access_count:\s*(\d+)') {
            $ac = [int]$matches[1]
            if ($ac -eq 0) { $never++ }
            if ($ac -gt 10) { $hot++ }
        }
        if ($body -match '(?m)^volatility:\s*stable') { $stable++ }
        elseif ($body -match '(?m)^volatility:\s*evolving') { $evolving++ }
        elseif ($body -match '(?m)^volatility:\s*ephemeral') { $ephemeral++ }
    }

    $logLines = 0
    if (Test-Path $logPath) { $logLines = (Get-Content $logPath -ErrorAction SilentlyContinue).Count }

    # Determine status
    $status = 'GREEN'
    if ($count -gt 150) { $status = 'YELLOW' }
    if ($count -gt 400) { $status = 'RED' }
    $stalePct = if ($count -gt 0) { ($stale180 / $count) * 100 } else { 0 }
    if ($stalePct -gt 10) { $status = 'YELLOW' }
    if ($stalePct -gt 25) { $status = 'RED' }

    # Days since last review — parse current HEALTH.md if present
    $daysSinceReview = 'n/a'
    $reviewLine = ''
    if (Test-Path $healthPath) {
        $hc = Get-Content $healthPath -Raw -ErrorAction SilentlyContinue
        if ($hc -and ($hc -match 'Last `/review` run:\s*(\S+)')) {
            $val = $matches[1]
            if ($val -ne 'never') {
                try {
                    $d = [datetime]::Parse($val)
                    $daysSinceReview = [int](($now - $d).TotalDays)
                    if ($daysSinceReview -gt 14) { $reviewLine = "**WEEKLY REVIEW OVERDUE — $daysSinceReview days. Run /review now.**" }
                    elseif ($daysSinceReview -gt 7)  { $reviewLine = "Weekly review due — $daysSinceReview days since last." }
                } catch {}
            }
        }
    }

    $avgWords = if ($count -gt 0) { [int]($totalWords / $count) } else { 0 }
    $stablePct = if ($count -gt 0) { [int](($stable / $count) * 100) } else { 0 }
    $evolvingPct = if ($count -gt 0) { [int](($evolving / $count) * 100) } else { 0 }
    $ephemeralPct = if ($count -gt 0) { [int](($ephemeral / $count) * 100) } else { 0 }

    $today = (Get-Date -Format 'yyyy-MM-dd')
    $health = @"
---
kind: health
last_updated: $today
status: $status
---

# Vault Health

Live dashboard for ``claude-memory/``. Regenerated by the SessionEnd hook.

## Weekly Review Status

- **Last ``/review`` run:** never (baseline)
- **Days since last review:** $daysSinceReview
- **Unresolved contradictions:** (run ``/contradictions`` to count)

$reviewLine

## Size

| Metric | Value |
|---|---|
| Topic page count | $count |
| Total word count | ~$totalWords |
| Average page size | ~$avgWords words |
| Max page size | ~$maxWords words |

## Retrieval Quality

| Metric | Value |
|---|---|
| Retrieval log lines | $logLines |
| Never-accessed topics | $never |
| Hot topics (>10 hits) | $hot |

## Freshness

| Metric | Value |
|---|---|
| Stale >60 days | $stale60 |
| Stale >180 days | $stale180 |

## Volatility Distribution

| Tier | Count | % |
|---|---|---|
| stable | $stable | $stablePct% |
| evolving | $evolving | $evolvingPct% |
| ephemeral | $ephemeral | $ephemeralPct% |

## Classification

**$status**

Regenerated $today.
"@

    Set-Content -Path $healthPath -Value $health -Encoding UTF8 -NoNewline
    Commit-Vault -Tag 'health' -Message "regenerated HEALTH.md ($status, $count topics)"

    if ($reviewLine) {
        Write-Output $reviewLine
    }
    exit 0
} catch {
    exit 0
}
