"""Render an ImprovementPrompt as a markdown file for the repo's knowledge/ dir."""

from __future__ import annotations

import re

from cortex.repo_review.analyzer import ImprovementPrompt
from cortex.utils.timezone import now_pacific


def render_prompt_md(
    *, repo: str, domain: str, idx: int,
    prompt: ImprovementPrompt, vault_hits: list[dict] | None = None,
) -> tuple[str, str]:
    """Return (filename, content) for one prompt."""
    slug = _slugify(prompt.title)
    filename = f"{idx:02d}-{slug}.md"

    cited_block = ""
    if prompt.cited_notes:
        cited_block = "## Cited evidence\n\n"
        for c in prompt.cited_notes:
            cited_block += f"- {c}\n"
        cited_block += "\n"

    front = (
        f"---\n"
        f"type: cortex-improvement-prompt\n"
        f"generated_by: cortex-repo-review\n"
        f"repo: {repo}\n"
        f"domain: {domain}\n"
        f"impact: {prompt.impact}\n"
        f"effort: {prompt.effort}\n"
        f"generated_at: {now_pacific().isoformat()}\n"
        f"---\n\n"
    )
    body = (
        f"# {prompt.title}\n\n"
        f"**Impact:** {prompt.impact}  ·  **Effort:** {prompt.effort}\n\n"
        f"## Rationale\n\n{prompt.rationale}\n\n"
        f"{cited_block}"
        f"## Prompt (paste into Claude Code from repo root)\n\n"
        f"```\n{prompt.prompt}\n```\n"
    )
    return filename, front + body


def render_index_md(*, repo: str, domain: str, summary: str,
                    prompts: list[ImprovementPrompt],
                    vault_hits: list[dict] | None = None) -> str:
    """Render the knowledge/README.md index."""
    head = (
        f"# Cortex Knowledge — `{repo}`\n\n"
        f"_Auto-generated by [Cortex](https://github.com/rjain557/rjain557-knowledge) "
        f"on {now_pacific().strftime('%Y-%m-%d %H:%M %Z')}._\n\n"
        f"**Primary domain:** {domain}\n\n"
        f"## Repo summary (Cortex's understanding)\n\n{summary}\n\n"
        f"## Improvement prompts\n\n"
    )
    for i, p in enumerate(prompts, 1):
        head += f"{i}. **[{p.title}]({i:02d}-{_slugify(p.title)}.md)** — _{p.impact} impact · {p.effort} effort_\n"
    head += "\nEach file contains a copy-paste prompt the dev runs in Claude Code (or Codex) "
    head += "to actually implement the improvement.\n\n"

    if vault_hits:
        head += "## Vault notes that informed these (top 5)\n\n"
        for v in vault_hits[:5]:
            head += f"- `{v['vault_path']}` — {v['title']} (distance {v['distance']:.3f})\n"

    head += "\n---\n\n_To pause repo reviews for this repo: remove it from `config/reviewed-repos.yaml` in the Cortex repo._\n"
    return head


def _slugify(text: str, max_len: int = 70) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_-]+", "-", text)
    return text.strip("-")[:max_len]
