"""Top-level orchestration for the daily repo-review pass.

Glues lister -> analyzer -> prompt_writer -> pr_writer together.
Callable from both the CLI (scripts/review_repos.py) and the webhook
server (POST /repo-review).
"""

from __future__ import annotations

import structlog

from cortex.repo_review.analyzer import analyze_repo
from cortex.repo_review.lister import get_repo_context, load_config
from cortex.repo_review.pr_writer import write_pr
from cortex.repo_review.prompt_writer import (
    render_index_md, render_prompt_md,
)
from cortex.utils.timezone import now_pacific

log = structlog.get_logger(__name__)


def review_one(*, full_name: str, domain: str,
               max_prompts: int, model: str,
               branch_prefix: str) -> dict:
    """Full pipeline for ONE repo. Returns a result dict."""
    ctx = get_repo_context(full_name)
    if ctx is None:
        return {"repo": full_name, "status": "context_failed"}

    analysis = analyze_repo(ctx, domain=domain, model=model,
                            max_prompts=max_prompts)
    if not analysis.improvements:
        return {"repo": full_name, "status": "no_improvements",
                "vault_hits": len(analysis.vault_hits)}

    files: dict[str, str] = {}
    for i, imp in enumerate(analysis.improvements, 1):
        fname, content = render_prompt_md(
            repo=full_name, domain=domain, idx=i, prompt=imp,
            vault_hits=analysis.vault_hits,
        )
        files[fname] = content
    files["README.md"] = render_index_md(
        repo=full_name, domain=domain, summary=analysis.summary,
        prompts=analysis.improvements, vault_hits=analysis.vault_hits,
    )

    today = now_pacific().strftime("%Y-%m-%d")
    pr_title = f"[cortex] Knowledge refresh {today} — {len(analysis.improvements)} improvement prompts"
    pr_body = (
        f"## Cortex daily repo review\n\n"
        f"This PR refreshes the `knowledge/` directory with {len(analysis.improvements)} "
        f"new improvement prompts informed by the Cortex knowledge brain "
        f"(domain: **{domain}**).\n\n"
        f"### Repo summary\n\n{analysis.summary}\n\n"
        f"### Improvements proposed\n\n"
        + "\n".join(
            f"- **{p.title}** — {p.impact} impact, {p.effort} effort"
            for p in analysis.improvements
        )
        + f"\n\n### Vault notes consulted ({len(analysis.vault_hits)})\n\n"
        + "\n".join(
            f"- `{v['vault_path']}` ({v['distance']:.3f})"
            for v in analysis.vault_hits[:5]
        )
        + "\n\n_Auto-generated by Cortex. Review each prompt before running."
        " To pause reviews for this repo, remove it from "
        "`config/reviewed-repos.yaml` in `rjain557/rjain557-knowledge`._"
    )

    pr_result = write_pr(
        full_name=full_name, default_branch=ctx.default_branch,
        knowledge_files=files, pr_title=pr_title, pr_body=pr_body,
        branch_prefix=branch_prefix,
    )
    return {"repo": full_name, "status": pr_result.status,
            "pr_number": pr_result.pr_number, "pr_url": pr_result.pr_url,
            "files": pr_result.files_written,
            "improvements": len(analysis.improvements),
            "vault_hits": len(analysis.vault_hits),
            "error": pr_result.error}


def run_daily(max_repos: int | None = None) -> dict:
    cfg = load_config()
    repos = cfg.get("repos", []) or []
    if max_repos is None:
        max_repos = int(cfg.get("max_repos_per_run", 5))
    max_prompts = int(cfg.get("max_prompts_per_repo", 5))
    model = cfg.get("analysis_model", "claude-sonnet-4-6")
    branch_prefix = cfg.get("pr_branch_prefix", "cortex-knowledge")

    log.info("repo_review.batch_start", planned=min(max_repos, len(repos)),
             max_prompts=max_prompts, model=model)

    results: list[dict] = []
    for entry in repos[:max_repos]:
        full_name = entry["name"]
        domain = entry.get("domain", "agent-orchestration")
        try:
            r = review_one(
                full_name=full_name, domain=domain,
                max_prompts=max_prompts, model=model,
                branch_prefix=branch_prefix,
            )
        except Exception as exc:
            log.error("repo_review.exception", repo=full_name,
                      error=str(exc)[:300])
            r = {"repo": full_name, "status": "exception",
                 "error": str(exc)[:300]}
        results.append(r)

    summary = {
        "repos_processed": len(results),
        "prs_opened": sum(1 for r in results
                          if r.get("status") == "ok" and r.get("pr_number")),
        "no_improvements": sum(1 for r in results
                               if r.get("status") == "no_improvements"),
        "failed": sum(1 for r in results
                      if r.get("status") in ("failed", "exception",
                                             "context_failed")),
        "results": results,
    }
    log.info("repo_review.batch_done", **{k: v for k, v in summary.items()
                                          if k != "results"})
    return summary
